### ISSUE TITLE
My Proposal:

### ISSUE THREAD

**Issue by remotevase** [TesseractTeam/Tesseract#100]
I propose that the TesseractTeam who are working on Tesseract join together with the H4PM team who are working on Elywing and create one amazing software. Since I am a member of the Tesseract Team, I think that members of both teams should talk here, as I am the one who is creating this proposal. 

NOTE: HOW INTERESTING! This is the 100th issue!

Other Note: To tesseract devs,
I have notified the elywing devs [in this issue](https://github.com/H4PM/Elywing/issues/285)

**Comment by remotevase** [comment]
The name of the proposed software has not been decided yet, and it will not be decided until we decide: Will the devs join together or stay apart?

**Comment by AppleDevelops** [comment]
I could see this as a good thing, we'd get features and fixes out fast.

**Comment by remotevase** [comment]
Yes, that is why I proposed this. I know that both teams are friendly, meaning that this could work very well

**Comment by xZeroMCPE** [comment]
hmn.... compulsive

**Comment by Nought57** [comment]
Your propose (create one amazing software) is good. but, I think the bug does not diminish. Why bug does not diminish? Because, The bug is caused by the Irresponsibility Commit. What is Irresponsibility Commit? Several Commit and many bugs are encountered. These results, We can know the Bugs caused by which Commit. But, Did not revert to the original. Not good to repeat this. Need to change Initiatives.

**Comment by Nought57** [comment]
We need to help each other. If you have it. we create one amazing software.

**Comment by remotevase** [comment]
,I agree

**Comment by RateekMCPE** [comment]
Yes :)

**Comment by AppleDevelops** [comment]
@remotevase They aren't going to say yes just face it
