### ISSUE TITLE
the existence of tesseract

### ISSUE THREAD

**Issue by CaitiffMCPE** [TesseractTeam/Tesseract#13]
the very existence of this offends me as well as my friends. you do not have what it takes to contribute to the main repo, huh? pathetic. you are probably scared, so scared that I can almost smell your fear, but hey - don't you think it would be better if everyone worked on the main repo together instead of making tons of repos? i doubt that you would even be of any use to us even if you were part of pmmp - you probably wouldn't be able to do simple actions, but strangely, i think n+1 people are better than n. so what do you prefer? watching how tesseract dies slowly... or deleting tesseract and moving to pmmp?  :)

**Comment by CaitiffMCPE** [comment]
i will also try to _"convince"_ others

**Comment by IISweePII** [comment]
Simply Tesseract is a spoon of Genisys and Elywing like our ReadMe part says, we can still contribute the same things to we just have different implementations that may not comply too well with Genisys and Elywing, since especially with 0.16 obviously a lot of stuff was changed, we don't conflict with other softwares like Genisys either. We aren't scared of anything as well since others can use our software too :)

I know that you are concerned but this is a project anyone can contribute to like Genisys and Elywing, we really intend no harm to others or other softwares since especially me and a few others are actively finding issues and seeing how to work with 0.16 to make a good running server. Sorry for any issues you have :)

**Comment by CaitiffMCPE** [comment]
the main point of my post was dodged. you are telling me things that i know and that are not of any use to me. all i am saying is, stop being cowards, contribute to the main repo

**Comment by IISweePII** [comment]
There was the point of the stuff that we have that may not comply with Genisys or Pmmp or Elywing, as we said before, we aren't scared, and even Genisys knows of Tesseract and has no problems. I even want to contribute our findings to Genisys, but I'm not sure what they'll say

**Comment by TheAppleGamer** [comment]
For one this argument doesn't need to be here, it's considered spam. Two, we don't open PRs to pmmp and Genisys because they most likely don't like our code we are working on. You can't say Tesseract will die because I know of 2 popular servers that use it. We weren't dodging the question and we are happy with what we have done, because in the end, there is always someone who likes this software and would prefer this over Genisys or pmmp.
