### ISSUE TITLE
Issues with Tesseract

### ISSUE THREAD

**Issue by KillerXtream** [TesseractTeam/Tesseract#16]
#### Problem description

Well, currently, I have two issues and one question.
- Issue 1: Slapper (Human/Other entities) spawn incorrectly, with a lead, without a nametag, or it crashes clients.
- Issue 2: Beacon system is pretty perfect, when you place a beacon with emerald or some gem block, you can see the ray generated by it, but after relogging/rebooting server, you won't be able to watch the ray again until you remove and replace again.
- Question 1: I run this server software as default with some modifications on my server hosting. I would like if we could make some partnership! Also, I'm a web PHP developer! 

#### Steps to reproduce the issue

- Issue 1: Slapper issue is not really with Slapper, not only entities generated by Slapper has this conflict.
- Issue 2: Make a beacon with any gem, relog, and you wont see the ray.#### OS and versions

* Tesseract: Crystal
* PHP: 7.0.2
* Server OS: RHEL7 
* Game version: 0.16.0

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```
P.D: Amazing repo! Best software for PE at 0.16

**Comment by TheAppleGamer** [comment]
Regarding first issue, you are most likely using an outdated slapper, and that causes the client crashing, the nametags in it is because Slapper hasn't updated some of their nametag code and that's why it rarely appears.

Second issue: Are the beacons in the same worlds as the player? If so I'll look it to it, but it sounds like a client issue, but it never hurts to try.

Regarding your question, I have a question to ask you.
What kind of partnership are you asking about?

Also thanks for calling our software great! 👍

**Comment by IISweePII** [comment]
You can tell us which version of Slapper you are using to see if having a older version of Slapper could be the reason why it seems to crash, thanks for bringing this issue so that we can know it and I'm glad that you are using Tesseract in your server :)

**Comment by KillerXtream** [comment]
### Answers for @TheAppleGamer 

- Answer 1: I'm not using an outdated Slapper, I use the 1.2.9.7 version.
- Answer 2: Yes, the beacons are placed at the spawn point.
- Answer 3: My hosting is going to be released soon, because this, I decided to run Tesseract as native MCPE server software, I'm pretty decent at standalone PHP, but I don't like PM API, so, I'm not very good with PocketMine development, we could share some resources, an example, a test server for Tesseract.

### Answer for @IISweePII 

- Answer 1: I'm using Slapper 1.2.9.7 on my servers.

**Comment by KillerXtream** [comment]
Thanks for answering fastly though! 

If you guys need something! Don't hesitate on asking me!

**Comment by KillerXtream** [comment]
Nevermind! I just found the Slapper update!! My mistake haha, then, the only problem is about the beacons

**Comment by TheAppleGamer** [comment]
@KillerXtream I'll be investigating beacons, do you by any chance have Twitter?

**Comment by KillerXtream** [comment]
Yeah, feel free to contact me @ kpwn_

**Comment by IISweePII** [comment]
@KillerXtream yeah the Slapper was a little outdated since the API and coding was changed, even though it was coded to load on 2.1.0, it may have different ways to load a entity into the server which 0.16 - 0.16.x may not like, at least its working now xD

**Comment by IISweePII** [comment]
@KillerXtream WE have fixed a good amount of issues thanks to people that can find them and tell us, and to ourselves since we test our software for any issues that 0.16 brings to the table, currently I am fixing the guardian enchant laser since it is a little too big (for example), and how we fixed the /gamemode error that was ticking especially me off haha + more stuffs

**Comment by KillerXtream** [comment]
Yeah! I see! Anyways, I have running a test server to check bugs and more things! If you guys need some server like this, don't hesitate on asking me, I'll make one for you guys!

**Comment by xZeroMCPE** [comment]
@KillerXtream  What do you mean by "make some partnership".

Anyways, I've tested this issue, and found the same thing. I think i may have a fix for it. 
I"ll be testing it, and will commit as soon as i can confirm it works.

**Comment by IISweePII** [comment]
@xZeroMCPE that's good to hear :)

**Comment by AppleDevelops** [comment]
@KillerXtream Beacons work now!
