### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by xZeroMCPE** [TesseractTeam/Tesseract#2]
Why not remove the PHP from the repo name?

it"ll make it more bright!

**Comment by TheAppleGamer** [comment]
I put TesseractPHP here as there is a second Tesseract coded in Python I just didn't want to make it confusing

**Comment by xZeroMCPE** [comment]
Oh..  Does the Python version works? if not  then f*** the Python version lol.....

The name without PHP sounds better....

**Comment by TheAppleGamer** [comment]
Python is not working ATM and I'm not sure if ImagicalGamer is coming back so I guess TesseractPHP is becoming Tesseract

**Comment by xZeroMCPE** [comment]
Then do that, and Python is actually bad when it comes to MCPE: Server softwares.

I can maybe try and contribute on this.

But again, You can always give it a try!

**Comment by TheAppleGamer** [comment]
I'll keep the Python version there for now lol but I just changed this one's repo name

**Comment by TheAppleGamer** [comment]
I'll be looking forward to more contributors lol

**Comment by xZeroMCPE** [comment]
Yeah, i see.

**Comment by Nought57** [comment]
@xZeroMCPE 
Sry, I will not be able to answer your expectations. because Tesseract is dead...
It became the same as when it was Imagical. Many src dies...
Have you seen the forum? His behavior is hated by users.
We added it to our members. Everything is right. The reputation fell. 
Since Apple is gone... Many developers are not working...

**Comment by Nought57** [comment]
Tesseract sleeps in peace...
It may be that Apple was right...
