### ISSUE TITLE
FloatingTextParticle not working

### ISSUE THREAD

**Issue by opkiler22789** [TesseractTeam/Tesseract#23]
#### Issue description
FloatingTextParticle not working!!

#### Steps to reproduce the issue
` $level->addParticle(new \pocketmine\level\particle\FloatingTextParticle(new Vector3(0 + 0.5, 0 + 2, 0), "","LOOOOOL"));`

#### OS and versions

* Tesseract: 1.2 (latest version)
* PHP: 7
* Server OS: Linux
* Game version: 1.1

**Comment by ondraczsk** [comment]
@opkiler22789 are you having any crash or error message? if yes, tell

**Comment by xZeroMCPE** [comment]
The reason why it's not working is due to (I think):

`new Vector3(0 + 0.5, 0 + 2, 0)`

The X returns 0.5, y returns: 2 and y return 0. 

You'd have to add it to a  correct Vector, but the one you have is currently still good. Try teleporting to that position and see if you see it.

But anyhow, make the XYZ somewhere you can see it so you can test it.

**Comment by ImagicalGamer** [comment]
Why would you do 0 + 0.5 anyway? That's very simple math I highly suggest you learn, anything added to 0 is itself 0 added to anything is itself.

**Comment by opkiler22789** [comment]
@ImagicalGamer @xZeroMCPE @ondraczsk  it looks like this:
<img width="960" alt="applicationframehost_2017-06-20_08-52-35" src="https://user-images.githubusercontent.com/17113289/27318592-eed39eb6-5595-11e7-8ae2-6419ab9ba5b7.png">
Code is fixed on:  `$level->addParticle(new \pocketmine\level\particle\FloatingTextParticle(new Vector3(496, 72, 286), "","LOL"));`

**Comment by opkiler22789** [comment]
fixed in #30
