### ISSUE TITLE
Timings & Dyed Water & FlowerPots

### ISSUE THREAD

**Issue by LordJoshie** [TesseractTeam/Tesseract#255]
Just took a gander and players been telling me when they add color to the water to dye their armor, the water doesn't change color. Perhaps an easy fix ? 

Also... Timings doesn't seem to work anymore. 
The website has a wonky message... something about paper, and tacos. 

Anywho... This ain't an important issues, just something I'm not sure if ya'll are aware of. Feel free to close this issue once it's been seen, possibly leaving it up for discussion still. 

Thanks my dudes ! 

EDIT:

Also, just noticing flowers can't be put into the pots. 
This worked on Genisys, I recall. 

Is it relatively easy to add ? With some basic instruction, I might be able to help with this.

**Comment by LordJoshie** [comment]
is Nought57 on a close issue power trip ? ....

**Comment by Nought57** [comment]
@LordJoshie Why did you think that it was powertrip? Problems related to Enhancement are described in ProjectList and close problems when there is no update for a certain period. This is because many people check to confirm a bug. Besides, these are duplications with other problems. I have them and I close the problem. I did not quit support. You seem to be dissatisfied with this, so I open up the problem again. Please close it freely if you think that the problem has been solved. Finally, Saying something carelessly can hurt the person that you are talking to. Do not forget it.

**Comment by LordJoshie** [comment]
You closed a few issies that had been tagged by the main dev of this...

no worries homeslice... was kust asking.

cuz randomly you went about closing many issuss that hadn't been
resolved...

such as placing plants in flower pots... not enchant related.
or colored water... considering applying the dye works, ans dying the armor
does, just the water isnt colored in the pot..

but yah. if u got hurt feelings thats more so the way you take things.... I
literally only asked if a power trip is what was going on due to the fact
you had closed issues with no response to them at all... they had been
tagged, and then you came along and closed them.
:)

**Comment by Nought57** [comment]
@LordJoshie 
"cuz randomly you went about closing many issuss that hadn't been
resolved..."
I'm sorry... I did not mean to make you uncomfortable...

It is a mistake that "I'm not the main developer" of this problem
I'm seeing this issues everyday.
but, I can not edit the code busily and satisfactorily.

"such as placing plants in flower pots... not enchant related."
Even if it is not attractive it is working on problem solving.
Because at least one person is asking for it.

**Comment by AppleDevelops** [comment]
I'd almost swear remote_vase 2.0 is starting to show

**Comment by Nought57** [comment]
@AppleDevelops Were not Tesseract's official policy to close the addition of ProjectList and closing Enhancement related issues? Or was it a dogmatic decision by remotevase? He said he was team policy...I sometimes comment, details are unknown. Which one is real...

**Comment by Nought57** [comment]
I understood. A serious mistake.

**Comment by Nought57** [comment]
@AppleDevelops I noticed a serious mistake. What I learned from "remote" has an adverse effect.

**Comment by LordJoshie** [comment]
you sound like you're about 13, trying prove himself...or herself....

relax dude...  just seemed edgy that you went on closing the issues without
so much as a "Has this been checked with other issues?... do you feel this
issue can be closed" ... nope, just like a pissed off mom cleaning her
son's room, you just came in here tossing things out left right & center.


this has gotten blown outta proportion tho.

maybe next time leave a comment on their issue to see if the person who
issued the issue is still active on their issue or not... lol.

Have a good day m'dudes ! Off to work !

**Comment by Hagg666** [comment]
a bug of the pot, I agree. this bug in the next version will remove the kernel?
