### ISSUE TITLE
Items are bugging so hard lol

### ISSUE THREAD

**Issue by Bluplayz** [TesseractTeam/Tesseract#309]
The items on Minecraft Windows 10 are bugged a lot of!
mostly the items go away to the chest. then if i equip a armor with right click and cancel the EntityEquipEvent and the PlayerInteractEvent, the equip can only see for myself lol

#### OS and versions

* Tesseract:
* PHP:
* Server OS:
* Game version: 
* Server host:
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by erkam2002** [comment]
The latest versions (commits) are not good tesseract is broken :/

**Comment by Bluplayz** [comment]
The funny thing is: nothing for the items have been changed lol most of all was the tiles xD

**Comment by erkam2002** [comment]
Bist du BluPlayz.de ts?

**Comment by Bluplayz** [comment]
yes but please only in english here ^^ we aren't the only who see this xD

**Comment by erkam2002** [comment]
Ik

**Comment by LordJoshie** [comment]
Hey m'dudes, I'd like you guys to learn how to make a test base for testing new versions of Tess, before reporting issues because a lot of the issues are the fact that something was missed... 

It WILL be fixed. 

Now, go have a look at the changes in the latest commits, see how many there are, then consider... damn... that's a lot of changes... I could only imagine how mentally frustrating it must be to keep track of all those changes.

Well, it's bloody difficult, and yet somehow... apple does a lot of these, frequently... so give the guy a break on the issue posting, and just keep an eye on things... most of the very most recent issues are known, and when Apple has time, I'm sure he will resolve this. 

Until then, revert back to an earlier version when things worked better for you. 

Also, please always include your setup, if you're not a known active updater/tester of Tess... we don't have a crystal ball to look through and see what your setup is, so include the version of your tess, use the /version command in game, and php version, as well as the OS of the machine you run your server on. 

PHP, TESS VERSION, AND HOST OS all have a major part to do with compatibility.... thats why it is asked of you guys in the issue report to include that information.

It wont always be assumed you have the latest of everything.

Thanks M'Dudes

**Comment by LordJoshie** [comment]
if you have the language issue, do this....

click this

https://github.com/TesseractTeam/Tesseract/tree/master/src/pocketmine/lang

click the locale @ 0951719 , download the folder, and copy these files to their directory.
src/pocketmine/lang/

**Comment by Bluplayz** [comment]
wtf my issue was the items not a language lol

**Comment by xZeroMCPE** [comment]
Follow issue template....
