### ISSUE TITLE
Multi Version Support

### ISSUE THREAD

**Issue by AydarTop** [TesseractTeam/Tesseract#430]
Hello. Can you add 1.0.4-1.0.5 multiprotocol?

**Comment by MCPEGamerJPatGitHub** [comment]
That is very dangerous

**Comment by LordJoshie** [comment]
Ench-ancement ? 

Is this some kind of pun on an enchanting enhancement... or just dumbass kids who can't spell ?

**Comment by ImagicalGamer** [comment]
We are working on this!

**Comment by LordJoshie** [comment]
wow... having a nice little label battle there eh. 

looks like a load of fun. 


why add multi version support ? that's stupid. how about these idiots needing support for older clients when the server updates just get off their shitty outdated hax launchers and shitty downloaded knockoff copies of MCPE, and update through their app store and play normally ? 

other than needing support for old client where hax still work, I don't see the need for multi version support... since Mojang usually drops their updates before servers do.

**Comment by SuperMaXAleX** [comment]
More players can join the server, that's all.

**Comment by LordJoshie** [comment]
so... you're telling me that more players can join off of different version, but the same amount of players couldn't join if they all had the same version ? that sounds pretty fuckin stupid if you ask me.

all I see is a way for players with outdated hax launchers to still join the game after it's been updated... allowing them the ability to keep using their shit hax launchers instead of being forced to update their game authentically and playing fair without modified launchers.

**Comment by LordJoshie** [comment]
add the label "HackedLauncherSupport" the this will make more sense...

**Comment by MalakasPlayzMC** [comment]
Why not creating a plugin that allows you to join with multiple protocols like AnyVersion in Nukkit?

**Comment by AydarTop** [comment]
@LordJoshie Multiprotocol support very important feature for MCPE server's. More player's use 1.0.0-1.0.4 version's.

**Comment by LordJoshie** [comment]
Well, fuck then ! lets just add support for PC to join also, and for older versions... like 0.11.0... why the hell not.... lets just make it so Pokemon game players can join also... makes sense. 

or.... how about this. 

if the server updates, it's because a client update is out... players can update their clients and play. 

otherwise, they are likely using a modified launcher or a downloaded (stolen) copy of Minecraft.. 
WHY WOULD YOU WANT TO SUPPORT THAT ?

**Comment by AydarTop** [comment]
@LordJoshie More player's are stupid kids. They can't update client or it's difficult for them.

**Comment by AppleDevelops** [comment]
Since all of you are going to whine and cry about it, this is now locked, anyone who makes an issue based on this just to whine will get banned.
